### ISSUE TITLE
Whitespace at bottom of app

### ISSUE THREAD

**Issue by wthompson40** [Ctrl-Alt-Delicious/CacheSimulator#3]
Dependent on L3 cache being present or not.

**Comment by jbonzo** [comment]
Currently there's white space at the bottom of the app as seen in the pic attached. This only happens when the app first opens up and no trace file is loaded. We do not want this white space.
<img width="1280" alt="screen shot 2017-09-09 at 10 55 12 am" src="https://user-images.githubusercontent.com/8647805/30241238-6bb14978-954d-11e7-81f9-364a748301cf.png">
