### ISSUE TITLE
Trace File Parser

### ISSUE THREAD

**Issue by ryan-berst** [Ctrl-Alt-Delicious/CacheSimulator#37]
Back-end component that parses a trace file and stores it in a data structure for use by the cache simulator.

**Comment by ryan-berst** [comment]
Just need to modify `fileParser.js` to divide address components based on provided parameters.

**Comment by jbonzo** [comment]
This issue addresses a bit more now. It sets defaults for the write policy and block size. These defaults open allow us to set defaults for L1 since the file cannot properly be parsed (more specifically the address cannot be broken down) until we know the Cache size, the aSsociativity, and the Block size. Then it parses the trace file and breaks the addresses down according the L1's specs.

TL;DR

* sets defaults for the following settings:
    * policy, B, L1C, L1S
* parses trace file and breaks apart address
